### ISSUE TITLE
soljson requestFile callback

### ISSUE THREAD

**Issue by axic** [chriseth/browser-solidity#84]
The `soljson` object now has two public methods, `compileJSON` and `compileJSONMulti` to process a JSON and generate Solidity bytecode. If any of them encounter an unmet import, they stop.

Would it be possible to include a synchronous callback to retrieve such a file?

E.g. compileJSON would have a third parameter (function): `cb(path)` to return the file contents as a string.

**Comment by axic** [comment]
If https://github.com/chriseth/browser-solidity/issues/82 is solved I am happy to look into this. I have written a wrapper which does that import, but it is not optimal as I need to "parse" the input solidity code.

**Comment by chriseth** [comment]
We are currently redesigning the way imports are done in Solidity: https://github.com/ethereum/wiki/wiki/Solidity-Features#more-flexible-import
Thanks for the suggestion, supplying a callback to resolve missing imports is a good thing to have for soljson.

**Comment by chriseth** [comment]
The callback is actually there now, but I did not manage to write the contents of the file into memory due to some reason. In general, I don't think there is a big use case for fetching file contents synchronously, but if you have it, I would be happy if you could take a look!

**Comment by axic** [comment]
Sure, happy to check the code - where can I find it?

Reading my original command I think I meant that `compileJSON` remains synchronous from the caller's perspective, but the callback for includes is of course asynchronous.

**Comment by chriseth** [comment]
The callback for fetching the content of files has to be synchronous, mostly because of the way solidity is compiled to javascript, at least we would need some features from emscripten to enable that (I think they exist, but could be hard to integrate). If your file-reading-callback is not synchronous, then it is probably not worth taking a look at that.

What you _could_ implement, though, is just aggregating a list of files that were not supplied to the compiler in the first place, then fetching them asynchronously and re-running the compiler.

**Comment by axic** [comment]
This is fixed now.
